name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby & Update RubyGems
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt-add-repository -y ppa:brightbox/ruby-ng
          sudo apt update
          sudo apt install -y ruby3.2 ruby3.2-dev build-essential
          gem update --system 3.3.22
          gem install bundler
      - name: Build the site in the jekyll/builder container
        run: |
          export JEKYLL_VERSION=3.8
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
